### ISSUE TITLE
Allow boolean in Key

### ISSUE THREAD

**Issue by benkuly** [JuulLabs/indexeddb#90]
Currently something like this is not possible:
```kotlin
store.index("hasBeenBackedUp").getAll(Key(false))
```
because boolean is prevented as type in `validateKeyTypes`.

**Comment by twyatt** [comment]
I believe this is because even in pure JavaScript, a boolean key is not supported: https://www.w3.org/TR/IndexedDB/#key-construct

Perhaps instead of boolean, use `1` to represent `true` and `0` for `false`?

Although, I would be happy to learn that I'm wrong and boolean is actually supported; if you find something indicating so.

**Comment by benkuly** [comment]
You are absolutely right, sorry. I just could not imagine that booleans are not allowed :see_no_evil:

**Comment by twyatt** [comment]
> You are absolutely right, sorry. I just could not imagine that booleans are not allowed 🙈

Ya, is surprised me too when I learned about that. 😱
